# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/shopping_cart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/shopping_cart.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cprotobuf/shopping_cart.proto\".\n\tAddToCart\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"x\n\x0f\x41\x64\x64ToCartResult\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.AddToCartResult.Type\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\x1d\n\x04Type\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"]\n\x08UserCart\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.UserCart.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')
)



_ADDTOCARTRESULT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='AddToCartResult.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_ADDTOCARTRESULT_TYPE)


_ADDTOCART = _descriptor.Descriptor(
  name='AddToCart',
  full_name='AddToCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='AddToCart.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='AddToCart.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=78,
)


_ADDTOCARTRESULT = _descriptor.Descriptor(
  name='AddToCartResult',
  full_name='AddToCartResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='AddToCartResult.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='AddToCartResult.item_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='AddToCartResult.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADDTOCARTRESULT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=200,
)


_USERCART_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='UserCart.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='UserCart.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='UserCart.ItemsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=295,
)

_USERCART = _descriptor.Descriptor(
  name='UserCart',
  full_name='UserCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='UserCart.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERCART_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=295,
)

_ADDTOCARTRESULT.fields_by_name['type'].enum_type = _ADDTOCARTRESULT_TYPE
_ADDTOCARTRESULT_TYPE.containing_type = _ADDTOCARTRESULT
_USERCART_ITEMSENTRY.containing_type = _USERCART
_USERCART.fields_by_name['items'].message_type = _USERCART_ITEMSENTRY
DESCRIPTOR.message_types_by_name['AddToCart'] = _ADDTOCART
DESCRIPTOR.message_types_by_name['AddToCartResult'] = _ADDTOCARTRESULT
DESCRIPTOR.message_types_by_name['UserCart'] = _USERCART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddToCart = _reflection.GeneratedProtocolMessageType('AddToCart', (_message.Message,), dict(
  DESCRIPTOR = _ADDTOCART,
  __module__ = 'protobuf.shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:AddToCart)
  ))
_sym_db.RegisterMessage(AddToCart)

AddToCartResult = _reflection.GeneratedProtocolMessageType('AddToCartResult', (_message.Message,), dict(
  DESCRIPTOR = _ADDTOCARTRESULT,
  __module__ = 'protobuf.shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:AddToCartResult)
  ))
_sym_db.RegisterMessage(AddToCartResult)

UserCart = _reflection.GeneratedProtocolMessageType('UserCart', (_message.Message,), dict(

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _USERCART_ITEMSENTRY,
    __module__ = 'protobuf.shopping_cart_pb2'
    # @@protoc_insertion_point(class_scope:UserCart.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _USERCART,
  __module__ = 'protobuf.shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:UserCart)
  ))
_sym_db.RegisterMessage(UserCart)
_sym_db.RegisterMessage(UserCart.ItemsEntry)


_USERCART_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
